source 'https://rubygems.org'

gem 'rails', '3.2.13'


gem 'sqlite3'
gem 'backbone-on-rails'

group :assets do
  gem 'handlebars_assets'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'