source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '3.2.13'
gem 'mongoid'
gem 'dotenv-rails'
gem 'metric_fu'
gem 'brakeman'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'